### ISSUE TITLE
Move all `client` functionality under `gorc`

### ISSUE THREAD

**Issue by levicook** [PeggyJV/gravity-bridge#105]
We would like to reduce the number of binaries our project ships and leverage the smaller configuration footprint gorc provides.

To achieve this, we’re going to move the functionality found within client, currently three subcommands, into gorc.

- cosmos-to-eth
- eth-to-cosmos
- deploy-erc20-representation

After each of these subcommands exist in gorc, we can remove the client crate from our project. We can also review their usability and plan some improvements. We know presently that deploy-erc20-representation is hard to use and can be improved by introducing a new Cosmos chain query to assist with mapping denoms to ERC-20 attributes (name,symbol,decimals).

**Comment by alexanderbez** [comment]
@levicook can this be closed?

**Comment by levicook** [comment]
Let's leave it open until `client` and references to it are removed (ie docs). Should be the last thing we need here & @hannydevelop is working on it.
