### ISSUE TITLE
Prometheus metrics for orchestrator

### ISSUE THREAD

**Issue by jackzampolin** [PeggyJV/gravity-bridge#124]
The orchestrator should expose some health monitoring metrics for operators to help ensure the proper operation of their systems and to avoid slashing. Some metrics that should be exposed:

- [x] last observed event nonce on the cosmos chain
- [x] last event nonce from the ethereum contract
- [ ] ethereum signatures and their corresponding nonces 
- [ ] failed transactions
- [x] height of both cosmos and ethereum chains
- [x] other things implementer sees!

**Comment by levicook** [comment]
Starting to work on this;

I'm going to 
- use / embed [axum](https://github.com/tokio-rs/axum)
- give [metics] it's own config section; mainly so user's can specify the listener address.
- borrow from the channels pattern in [this example](https://github.com/tokio-rs/axum/blob/5c123288924bbda5eb193927607112677b0f8ac9/examples/chat.rs)

**Comment by levicook** [comment]
Got the basic framework in place today. Here's what have implemented (and need to test :))
 - [ ] "cosmos_unavailable", "cosmos chain was unavailable"
 - [ ] "cosmos_block_height", "cosmos chain block height"
 - [ ] "cosmos_last_event_nonce", "last event nonce committed by this validator"
 - [ ] "ethereum_last_event_nonce", "last event nonce on the gravity contract"
 - [ ] "ethereum_event_check_failures", "ethereum events could not be retrieved"
 - [ ] "ethereum_unavailable", "ethereum chain was unavailable"
 - [ ] "ethereum_block_height", "ethereum chain block height"
 - [ ] "ethereum_check_for_events_starting_block", "start of block range being scanned ethereum events"
 - [ ] "ethereum_check_for_events_end_block", "end of block range being scanned ethereum events"
 - [ ] "unsigned_batch_failures", "unsigned batches could not be retrieved"
 - [ ] "unsigned_logic_call_failures", "unsigned logic calls could not be retrieved"
 - [ ] "unsigned_valset_failures", "unsigned valsets could not be retrieved"

**Comment by levicook** [comment]
failed transactions should be easy; but still needs to be addressed.

**Comment by levicook** [comment]
"ethereum signatures and their corresponding nonces" 🤔  -- I _think_ I know what you mean here & can take a stab at it.

**Comment by levicook** [comment]
Here's a quick demo of the metrics produced during an end-to-end test run:

```
$ docker exec -it orchestrator0 curl --silent localhost:3000 | grep -v '#'
cosmos_block_height{chain="cosmos"} 316
cosmos_last_event_nonce{chain="cosmos"} 4
ethereum_block_height{chain="ethereum"} 126
ethereum_check_for_events_end_block{chain="ethereum"} 122
ethereum_check_for_events_starting_block{chain="ethereum"} 121
ethereum_event_check_failures{chain="ethereum"} 3
ethereum_last_batch_event{chain="ethereum"} 4
ethereum_last_batch_nonce{chain="ethereum"} 1
ethereum_last_erc20_block{chain="ethereum"} 18
ethereum_last_erc20_event{chain="ethereum"} 2
ethereum_last_event_nonce{chain="ethereum"} 4
ethereum_last_valset_event{chain="ethereum"} 3
ethereum_last_valset_nonce{chain="ethereum"} 1
```

**Comment by levicook** [comment]
We have our 1st pass PR on this merged & it will go out in the next testnet.
