### ISSUE TITLE
small refactor todos

### ISSUE THREAD

**Issue by jtremback** [PeggyJV/gravity-bridge#17]
This is a big list of todos that came up during the refactor of the Go module.

- [x] **Pluralize repeated fields in proto files**: Some of the proto structs have repeated fields which are not plural (eg `signature` vs `signatures`).
- [ ] **Audit use of the name "Outgoing"**: The old code used words like `OutgoingTx`, `OutgoingPool`, etc. to refer to the thing that is now known as `SendToEthereum`. We now use the word `OutgoingTx` to refer to something completely different. We need to carefully find old uses of this term (requires in depth knowledge of the system to make sure it isn't the new use of the term) and change them to `SendToEthereum`.
- [ ] **Audit use of "Create" vs "Build" vs "New"**: Both the Create and Build prefixes generally indicate a method that does something somewhat complicated and stateful to make a new entity of some kind. We should standardize on one or the other. "New" usually indicates a simpler instantiation of a struct, which does not mutate other state, but in some places it is doing something more and we should replace it with Create or Build.
- [ ] **Nonce prefixing**: We have many different nonces, including BatchNonce, SignerSetNonce, EventNonce, etc. Some data structures have two nonces. Mixing up nonces usually leads directly to a double spend error or something similarly dire, so we should prefix all nonce variables and fields with their type. Fixing this issue requires pretty in depth knowledge of what the different nonces are.
- [ ] **BridgeContract vs BridgeEthereumAddress**: Make sure this is consistent everywhere.
- [ ] **Deprecated slash fraction params**: We currently have different parameters for slashing of different types of OutgoingTxs. Unify them into one parameter (unless there is a need to actually slash different amounts).
- [x] **Audit all Validate and ValidateBasic functions, especially on Msgs**
- [ ] **Decide on, and likely remove MsgRequestBatch**: This message allows anyone to request that a batch of SendToEthereums for a given token be created. By spamming this endpoint, an adversary could cause a large number of batches with only a small number of transactions in each batch to be created, which would not be profitable to submit, and would effectively halt the bridge. We have now moved to automatic batch creation, so this message should no longer be necessary.
- [ ] **Double check that any denoms passed in are validated correctly**
- [x] **Validation for ContractCallTx**: ContractCallTxs are created by trusted external modules, calling a keeper method. We do not need to validate them for security reasons, but it might be nice to validate them for the convenience of calling module authors debugging. 
- [x] **Use bools in proto messages instead of magic values**: We have many proto request messages that either return an array of many results, or only the latest result. Currently, the caller indicates they want the latest result by passing in a magic value like 0 or "". This has already caused programming errors in the short time it's been around. We should switch to an explicit "latest" boolean in the request.
- [x] **Check if any iterators can be exited early**: There are many iterators in the codebase that can be exited early by returning `true`. There may be some that could be exited early, but are not, wasting iterations.

- [x] **Rename PendingSignerSetTxEthereumSignaturesRequest to UnsignedSignerSetTxsRequest**: This is much more readable and accurate.

**Comment by mvid** [comment]
Re: magic values, what happens if I pass in a valid nonce and also set latest to true? What if the latest and the passed in nonce don't match?

**Comment by jtremback** [comment]
We could use something like this: https://developers.google.com/protocol-buffers/docs/proto#oneof

But I think it's easy enough to just have it ignore the passed nonce if you set the "latest" boolean.

The other option would simply be to have an explicit request for latest, but that's what we just refactored away from.

**Comment by mvid** [comment]
I would vote to make it explicit, either with OneOf or separate requests. 0 nonce is a little interesting because it's the only invalid nonce value, since we are unsigned and start at 1. I have seen other APIs use 0 or -1 or nil as a special case value

**Comment by jackzampolin** [comment]
I'm also fine reverting to having separate latest routes.

**Comment by levicook** [comment]
I'm going to take a quick shot at using `oneof` on a PR for the magic value issue this afternoon. I think it might express our intention more clearly & am curious to see what it looks like, esp from a Rust perspective.

**Comment by levicook** [comment]
`oneof` makes things worse (at least for this use-case) -- I couldn't find a version on Saturday that even felt worth reviewing and think we should just use separate routes.
