### ISSUE TITLE
Cleaning batch fails with nil pointer exception

### ISSUE THREAD

**Issue by thomas-nguy** [PeggyJV/gravity-bridge#343]
The executed code will try to delete an non existing batch. This is cause by the wrong token address which is passed in parameters

Stack trace here :

Jan 27 05:35:23 ip-10-202-4-171 cronosd[114810]: 5:35AM ERR CONSENSUS FAILURE!!! err="runtime error: invalid memory address or nil pointer dereference" module=consensus server=node stack="goroutine 276 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x88\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2(0x4000fa1180, 0x25ac9f8)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:726 +0x48\npanic({0x1b4f0e0, 0x380df40})\n\t/usr/local/go/src/runtime/panic.go:1038 +0x224\ngithub.com/peggyjv/gravity-bridge/module/x/gravity/keeper.Keeper.CancelBatchTx({{0x28956a0, 0x4000e58420}, {0x28324c8, 0x4000ed28d0}, {{0x2890aa8, 0x40013fe350}, 0x4001408018, {0x28324c8, 0x4000ed2780}, {0x2832518, ...}, ...}, ...}, ...)\n\t/go/pkg/mod/github.com/peggyjv/gravity-bridge/module@v0.2.24-0.20211206214839-d22e7091a41d/x/gravity/keeper/batch.go:133 +0xc4\ngithub.com/peggyjv/gravity-bridge/module/x/gravity/keeper.Keeper.batchTxExecuted.func1({0x40043894e2, 0x1c, 0x1e}, {0x2840440, 0x4009fe8a00})\n\t/go/pkg/mod/github.com/peggyjv/gravity-bridge/module@v0.2.24-0.20211206214839-d22e7091a41d/x/gravity/keeper/batch.go:89 +0x154\ngithub.com/peggyjv/gravity-bridge/module/x/gravity/keeper.Keeper.IterateOutgoingTxsByType({{0x28956a0, 0x4000e58420}, {0x28324c8, 0x4000ed28d0}, {{0x2890aa8, 0x40013fe350}, 0x4001408018, {0x28324c8, 0x4000ed2780}, {0x2832518, ...}, ...}, ...}, ...)\n\t/go/pkg/mod/github.com/peggyjv/gravity-bridge/module@v0.2.24-0.20211206214839-d22e7091a41d/x/gravity/keeper/keeper.go:468 +0x294\ngithub.com/peggyjv/gravity-bridge/module/x/gravity/keeper.Keeper.batchTxExecuted({{0x28956a0, 0x4000e58420}, {0x28324c8, 0x4000ed28d0}, {{0x2890aa8, 0x40013fe350}, 0x4001408018, {0x28324c8, 0x4000ed2780}, {0x2832518, ...}, ...}, ...}, ...)\n\t/go/pkg/mod/github.com/peggyjv/gravity-bridge/module@v0.2.24-0.20211206214839-d22e7091a41d/x/gravity/keeper/batch.go:85 +0x168\ngithub.com/peggyjv/gravity-bridge/module/x/gravity/keeper.Keeper.Handle({{0x28956a0, 0x4000e58420}, {0x28324c8, 0x4000ed28d0}, {{0x2890aa8, 0x40013fe350}, 0x4001408018, {0x28324c8, 0x4000ed2780}, {0x2832518, ...}, ...}, ...}, ...)\n\t/go/pkg/mod/github.com/peggyjv/gravity-bridge/module@v0.2.24-0.20211206214839-d22e7091a41d/x/gravity/keeper/ethereum_event_handler.go:51 +0x2c8\ngithub.com/peggyjv/gravity-bridge/module/x/gravity/keeper.Keeper.processEthereumEvent({{0x28956a0, 0x4000e58420}, {0x28324c8, 0x4000ed28d0}, {{0x2890aa8, 0x40013fe350}, 0x4001408018, {0x28324c8, 0x4000ed2780}, {0x2832518, ...}, ...}, ...}, ...)\n\t/go/pkg/mod/github.com/peggyjv/gravity-bridge/module@v0.2.24-0.20211206214839-d22e7091a41d/x/gravity/keeper/ethereum_event_vote.go:121 +0x11c\ngithub.com/peggyjv/gravity-bridge/module/x/gravity/keeper.Keeper.TryEventVoteRecord({{0x28956a0, 0x4000e58420}, {0x28324c8, 0x4000ed28d0}, {{0x2890aa8, 0x40013fe350}, 0x4001408018, {0x28324c8, 0x4000ed2780}, {0x2832518, ...}, ...}, ...}, ...)\n\t/go/pkg/mod/github.com/peggyjv/gravity-bridge/module@v0.2.24-0.20211206214839-d22e7091a41d/x/gravity/keeper/ethereum_event_vote.go:96 +0x458\ngithub.com/peggyjv/gravity-bridge/module/x/gravity.eventVoteRecordTally({{0x28694c8, 0x40001a0000}, {0x2895620, 0x4009f9e600}, {{0xb, 0x0}, {0x400869f640, 0x1a}, 0x8c30f, {0x2d4ba316, ...}, ...}, ...}, ...)\n\t/go/pkg/mod/github.com/peggyjv/gravity-bridge/module@v0.2.24-0.20211206214839-d22e7091a41d/x/gravity/abci.go:147 +0x318\ngithub.com/peggyjv/gravity-bridge/module/x/gravity.EndBlocker({{0x28694c8, 0x40001a0000}, {0x2895620, 0x4009f9e600}, {{0xb, 0x0}, {0x400869f640, 0x1a}, 0x8c30f, {0x2d4ba316, ...}, ...}, ...}, ...)\n\t/go/pkg/mod/github.com/peggyjv/gravity-bridge/module@v0.2.24-0.20211206214839-d22e7091a41d/x/gravity/abci.go:30 +0xac\ngithub.com/peggyjv/gravity-bridge/module/x/gravity.AppModule.EndBlock(...)\n\t/go/pkg/mod/github.com/peggyjv/gravity-bridge/module@v0.2.24-0.20211206214839-d22e7091a41d/x/gravity/module.go:159\ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(0x40011e44d0, {{0x28694c8, 0x40001a0000}, {0x2895620, 0x4009f9e600}, {{0xb, 0x0}, {0x400869f640, 0x1a}, 0x8c30f, ...}, ...}, ...)\n\t/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.5/types/module/module.go:481 +0x268\ngithub.com/crypto-org-chain/cronos/app.(*App).EndBlocker(...)\n\t/go/src/github.com/crypto-org-chain/cronos/app/app.go:761\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0x40005c11e0, {0x8c30f})\n\t/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.5/baseapp/abci.go:210 +0x20c\ngithub.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0x40005c60c0, {0x8c30f})\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:288 +0xf4\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0x40010fea20, {0x8c30f})\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:89 +0x3c\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0x286a300, 0x400141a780}, {0x287ff50, 0x40010fea20}, 0x4009c4a960, {0x288ede8, 0x40011858b0}, 0x1)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/state/execution.go:327 +0x4b8\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0x40002de000, {{{0xb, 0x0}, {0x4000fe8344, 0x7}}, {0x40013fcf00, 0x1a}, 0x1, 0x8c30e, {{0x40082ca900, ...}, ...}, ...}, ...)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/state/execution.go:140 +0x108\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0x4000fa1180, 0x8c30f)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:1635 +0x964\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0x4000fa1180, 0x8c30f)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:1546 +0x324\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1(0x4000fa1180, 0x0, 0x8c30f)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:1481 +0x94\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0x4000fa1180, 0x8c30f, 0x0)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:1519 +0xc30\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0x4000fa1180, 0x40064febe0, {0x4004500d50, 0x28})\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:2132 +0xc48\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0x4000fa1180, 0x40064febe0, {0x4004500d50, 0x28})\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:1930 +0x40\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0x4000fa1180, {{0x28225a0, 0x4004e515e0}, {0x4004500d50, 0x28}})\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:838 +0x388\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0x4000fa1180, 0x0)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:762 +0x324\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:378 +0x120\n"

**Comment by EricBolten** [comment]
Thanks for the details Thomas, closing after the merge of https://github.com/PeggyJV/gravity-bridge/pull/342
