### ISSUE TITLE
Handle MAX_INT_256 and malicious ER20 sends

### ISSUE THREAD

**Issue by zmanian** [PeggyJV/gravity-bridge#44]
1. We need a pull request on the Cosmos SDK upstream to increase the maxBitLength of SDK.Int to 257 bits to ensure and a test the check the SDK.Int can deserialize the max ERC20 value.

```
`_, err := sdk.NewIntFromString("115792089237316195423570985008687907853269984665640564039457584007913129639935")`
``` 

should be in the test case.

We need a check in 

`func (a EthereumEventProcessor) Handle` to ensure that adding the amount send to Cosmos doesn't overflow the max size of SDK.Int. 

If it does overflow we should increment the event nonce but ignore the amount sent.

**Comment by jtremback** [comment]
> If it does overflow we should increment the event nonce but ignore the amount sent.

I think it already does work this way, as a natural outcome of ctx.CacheContext on https://github.com/PeggyJV/gravity-bridge/blob/main/module/x/gravity/keeper/ethereum_event_vote.go#L120

**Comment by albertchon** [comment]
https://github.com/cosmos/cosmos-sdk/pull/9511 closes this issue

**Comment by zmanian** [comment]
I don't see anything in ctx.CacheContext that will catch a panic. I think this only handles an error and not a panic.

**Comment by zmanian** [comment]
We need a panic handler here. Not just an error handler.

**Comment by albertchon** [comment]
FYI we fixed this in our fork without a panic handler
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/20461629/122169560-88ec7900-ce4b-11eb-91e9-3f8b90ca7cff.png">
